format-version = 1

[descriptors.'cpython-3.10']
language-descriptors = { python = 'cpython-3.10' }
title = 'Python 3.10'

[descriptors.'cpython-3.11']
language-descriptors = { python = 'cpython-3.11' }
title = 'Python 3.11'

[descriptors.'pypy-3.10']
language-descriptors = { python = 'pypy-3.10' }
title = 'PyPy 3.10'
