name: python-venv
description: 'Clones project, configures Python, and populates virtual environment.'
inputs:
  python-version:
    description: 'Version of the Python interpreter.'
    required: true
    default: '3.7'
  python-configure-flags:
    description: 'Flags to pass to the configure script for Python builds.'
    required: false
runs:
  using: composite
  steps:
    - name: Clone Repository Code
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Asdf Core and Plugins
      uses: asdf-vm/actions/plugins-add@v1
    - name: Select Python Version (if requested)
      if: "${{ 'all' != inputs.python-version }}"
      run: |
        set -eu
        python_version="$(asdf latest python ${{ inputs.python-version }})"
        echo "ASDF_PYTHON_VERSION=${python_version}" >>${GITHUB_ENV}
      shell: bash
    - name: Add Python Configure Flags (if requested)
      if: "${{ inputs.python-configure-flags }}"
      run: |
        set -eu
        echo 'PYTHON_CONFIGURE_OPTS=${{ inputs.python-configure-flags }}' >>${GITHUB_ENV}
      shell: bash
    - name: Install Managed Versions
      run: asdf install
      shell: bash
    - name: Install Invoke
      run: |
        set -eu
        python -m pip install --upgrade invoke pip setuptools wheel
        asdf reshim python
      shell: bash
    - name: Create Virtual Environments
      run: |
        set -eu
        invoke build-python-venv --version ALL
        asdf reshim python
      shell: bash
