name: python-venv
description: 'Clones project, configures Python, and populates virtual environment.'
inputs:
  python-version:
    description: 'Version of the Python interpreter.'
    required: true
    default: 3.6
runs:
  using: composite
  steps:
    - name: Clone Repository Code
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Procure Baseline Python
      uses: actions/setup-python@v2
      with:
        python-version: '${{ inputs.python-version }}'
    - name: Install Pipenv
      run: |
        set -e
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade pipenv
      shell: bash
    - name: Create Virtual Environment
      run: |
        set -eu
        # Note: 'pipenv --skip-lock --dev' does not work properly as of 2012-12-12.
        mv Pipfile.lock old-Pipfile.lock
        trap "mv --force old-Pipfile.lock Pipfile.lock" ERR EXIT
        # Properly handle versions like 'pypy-3.8'.
        python_version=$(echo ${{ inputs.python-version }} | awk -F- '{print $NF}')
        pipenv --python ${python_version} install --dev
      shell: bash
