name: python-venv
description: 'Clones project, configures Python, and populates virtual environment.'
inputs:
  python-version:
    description: 'Version of the Python interpreter.'
    required: true
    default: '3.7'
  python-configure-flags:
    description: 'Flags to pass to the configure script for Python builds.'
    required: false
runs:
  using: composite
  steps:
    - name: Clone Repository Code
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Asdf Core
      run: |
        set -eu
        asdf_install_path="${HOME}/.asdf"
        git clone --depth 1 --branch master https://github.com/asdf-vm/asdf.git "${asdf_install_path}"
        echo "ASDF_DIR=${asdf_install_path}" >>${GITHUB_ENV}
        echo "${asdf_install_path}/bin" >>${GITHUB_PATH}
        echo "${asdf_install_path}/shims" >>${GITHUB_PATH}
      shell: bash
    - name: Install Asdf Python Plugin
      run: |
        set -eu
        asdf plugin add python
        # https://github.com/danhper/asdf-python/issues/140
        cd ${ASDF_DIR}/plugins/python
        git checkout dcba495647619956c48914dc2e96710f398ec24a
      shell: bash
    - name: Select Python Version (if requested)
      if: "${{ 'all' != inputs.python-version }}"
      run: |
        set -eu
        python_version="$(asdf latest python ${{ inputs.python-version }})"
        echo "ASDF_PYTHON_VERSION=${python_version}" >>${GITHUB_ENV}
      shell: bash
    - name: Add Python Configure Flags (if requested)
      if: "${{ inputs.python-configure-flags }}"
      run: |
        set -eu
        echo 'PYTHON_CONFIGURE_OPTS=${{ inputs.python-configure-flags }}' >>${GITHUB_ENV}
      shell: bash
    - name: Install Managed Versions
      run: asdf install
      shell: bash
    - name: Create Virtual Environments
      run: |
        set -eu
        python3 develop.py build-python-venv --version ALL
        asdf reshim python
      shell: bash
