# TODO: Rework parser to support format version.
#format-version = 1

# References:
#   PEP 508 ("Dependency specification for Python Software Packages"):
#     https://peps.python.org/pep-0508/

installation = [ ]

[optional-installation]

[development]
base = [
  'invoke',
  'shellingham',
  'tomli',
  'tomli-w',
]
format = [
  # YAPF 0.31 is missing full support for 'yapf-diff'.
  'yapf >= 0.32',
]
documentation = [
  'furo',
  'sphinx',
  'sphinx-copybutton',
  'sphinx-inline-tabs',
]
lint = [
  'bandit',
  # Mypy relies on 'typed_ast', which does not build under PyPy 3.7.
  #   https://github.com/python/typed_ast/issues/111
  'mypy; implementation_name != "pypy" or python_version >= "3.8"',
  'pre-commit',
  # Pylint relies on 'typed_ast', which does not build under PyPy 3.7.
  #   https://github.com/python/typed_ast/issues/111
  # Pylint 2.15.2 requires a patch release of Astroid 2.12, which fixes:
  #   https://github.com/PyCQA/astroid/issues/1755
  'pylint >= 2.15.2; implementation_name != "pypy" or python_version >= "3.8"',
  'safety',
  # PyPy is quite sensitive to a data race in Semgrep (as of 0.111.1).
  #   https://github.com/returntocorp/semgrep/issues/5996
  'semgrep; implementation_name != "pypy"',
]
publication = [
  'bump2version',
  'twine',
]
test = [
  # Coverage 6.1 series breaks how we handle .gitignore files.
  'coverage[toml] >= 6.2',
  'hypothesis',
  'pytest',
]
