# References:
#   PEP 508 ("Dependency specification for Python Software Packages"):
#     https://peps.python.org/pep-0508/

installation = [ ]

[optional-installation]

[development]
format = [
  # YAPF 0.31 is missing full support for 'yapf-diff'.
  'yapf >= 0.32',
]
documentation = [
  'furo',
  'sphinx',
  'sphinx-copybutton',
  'sphinx-inline-tabs',
]
lint = [
  'bandit',
  # Mypy relies on 'typed_ast', which does not build under PyPy 3.7.
  #   https://github.com/python/typed_ast/issues/111
  'mypy; implementation_name != "pypy" or python_version >= "3.8"',
  'pre-commit',
  # Pylint relies on 'typed_ast', which does not build under PyPy 3.7.
  #   https://github.com/python/typed_ast/issues/111
  'pylint; implementation_name != "pypy" or python_version >= "3.8"',
  'safety',
  'semgrep',
]
management = [
  'bump2version',
  'invoke',
  'tomli',
  'tomli-w',
  'twine',
]
test = [
  # Coverage 6.1 series breaks how we handle .gitignore files.
  'coverage[toml] >= 6.2',
  'hypothesis',
  'pytest',
]
