format-version = 1

# References:
#   PEP 508 ("Dependency specification for Python Software Packages"):
#     https://peps.python.org/pep-0508/

[development]
documentation = [
  'furo',
  'sphinx',
  'sphinx-copybutton',
  'sphinx-inline-tabs',
]
publication = [
  'bump2version',
  'twine',
]

[[development.base]]
requirement = 'invoke @ git+https://github.com/emcd/invoke.git@fb40a3c79b3fa59cb589a642d0c4b8fa87ca082e'
comments = [
  ''' Invoke is broken on Python 3.11 because of removal of 'inspect.getargspec'.
      https://github.com/pyinvoke/invoke/issues/833
      Fork of repository is used as workaround for now. ''',
]

[[development.base]]
requirement = 'lockup'

[[development.base]]
requirement = 'shellingham'

[[development.base]]
requirement = 'tomli'

[[development.base]]
requirement = 'tomli-w'

[[development.format]]
requirement = 'yapf >= 0.32'
comments = [
  ''' YAPF 0.31 is missing full support for 'yapf-diff'. ''',
]

[[development.lint]]
requirement = 'bandit'

[[development.lint]]
requirement = 'mypy; implementation_name != "pypy" or python_version >= "3.8"'
comments = [
  ''' Mypy relies on 'typed_ast', which does not build under PyPy 3.7.
      https://github.com/python/typed_ast/issues/111 ''',
]

[[development.lint]]
requirement = 'pre-commit'

[[development.lint]]
requirement = 'pylint >= 2.15.2; implementation_name != "pypy" or python_version >= "3.8"'
comments = [
  ''' Pylint relies on 'typed_ast', which does not build under PyPy 3.7.
      https://github.com/python/typed_ast/issues/111 ''',
  ''' Pylint 2.15.2 requires a patch release of Astroid 2.12, which fixes:
      https://github.com/PyCQA/astroid/issues/1755 ''',
]

[[development.lint]]
requirement = 'safety'

[[development.lint]]
requirement = 'semgrep >= 0.114.0'
comments = [
  ''' Semgrep 0.114.0 includes fix for race with garbarge collector on PyPy.
      https://github.com/returntocorp/semgrep/pull/6100 '''
]

[[development.test]]
requirement = 'coverage[toml] >= 6.2'
comments = [
  ''' Coverage 6.1 series breaks how we handle .gitignore files. '''
]

[[development.test]]
requirement = 'hypothesis'

[[development.test]]
requirement = 'pytest'
