format-version = 1

# References:
#   PEP 508 ("Dependency specification for Python Software Packages"):
#     https://peps.python.org/pep-0508/

[development]
documentation = [
  'furo',
  'sphinx',
  'sphinx-copybutton',
  'sphinx-inline-tabs',
]
packaging = [
  'build',
]
publication = [
  'bump2version',
  'twine',
]

[[development.format]]
requirement = 'yapf >= 0.32'
comments = [
  ''' YAPF 0.31 is missing full support for 'yapf-diff'. ''',
]

[[development.lint]]
requirement = 'bandit[toml] @ git+https://github.com/PyCQA/bandit.git@d9fe642e01866e460454641bcd14b9de9d2b1478'
comments = [
  ''' Bandit 1.7.4, released 2022-03-03, relies on 'toml' rather than 'tomli'.
      The 'toml' package does not support the latest TOML standard
      and breaks on our 'pyproject.toml'. ''',
]

[[development.lint]]
requirement = 'mypy; implementation_name != "pypy" or python_version >= "3.8"'
comments = [
  ''' Mypy relies on 'typed_ast', which does not build under PyPy 3.7.
      https://github.com/python/typed_ast/issues/111 ''',
]

[[development.lint]]
requirement = 'pre-commit'

[[development.lint]]
requirement = 'pylint >= 2.15.2; implementation_name != "pypy" or python_version >= "3.8"'
comments = [
  ''' Pylint relies on 'typed_ast', which does not build under PyPy 3.7.
      https://github.com/python/typed_ast/issues/111 ''',
  ''' Pylint 2.15.2 requires a patch release of Astroid 2.12, which fixes:
      https://github.com/PyCQA/astroid/issues/1755 ''',
]

[[development.lint]]
requirement = 'safety'

[[development.lint]]
requirement = 'semgrep >= 0.114.0'
comments = [
  ''' Semgrep 0.114.0 includes fix for race with garbarge collector on PyPy.
      https://github.com/returntocorp/semgrep/pull/6100 '''
]

[[development.test]]
requirement = 'coverage[toml] >= 6.2'
comments = [
  ''' Coverage 6.1 series breaks how we handle .gitignore files. '''
]

[[development.test]]
requirement = 'hypothesis'

[[development.test]]
requirement = 'pre-commit'

[[development.test]]
requirement = 'pytest'
