[development]
format = [
  # Latest release of YAPF is missing full support for 'yapf-diff'
  # and hence a Git commit hash is used instead. (As of 2021-12-23.)
  'yapf @ git+https://github.com/google/yapf.git@9d6808a3d9b9a0ea40efea0c7cc3247464dbc291',
]
documentation = [
  'furo',
  'sphinx',
  'sphinx-copybutton',
  'sphinx-inline-tabs',
]
lint = [
  'bandit',
  # Mypy relies on 'typed_ast', which does not build under PyPy. (As of 2021-12-23.)
  'mypy; implementation_name != "pypy"',
  'pre-commit',
  # Pylint relies on 'typed_ast', which does not build under PyPy. (As of 2021-12-23.)
  'pylint; implementation_name != "pypy"',
  'semgrep',
]
management = [
  'bump2version',
  'invoke',
  'tomli',
  'twine',
]
test = [
  # Coverage 6.1 series breaks how we handle .gitignore files.
  'coverage[toml] >= 6.2',
  'hypothesis',
  'pytest',
  'tox',
  'tox-asdf',
]

[installation]

[optional-installation]
