[development]
format = [
  # YAPF 0.31 is missing full support for 'yapf-diff'.
  'yapf >= 0.32',
]
documentation = [
  'furo',
  'sphinx',
  'sphinx-copybutton',
  'sphinx-inline-tabs',
]
lint = [
  'bandit',
  # Mypy relies on 'typed_ast', which does not build under PyPy. (As of 2021-12-23.)
  'mypy; implementation_name != "pypy"',
  'pre-commit',
  # Pylint relies on 'typed_ast', which does not build under PyPy. (As of 2021-12-23.)
  'pylint; implementation_name != "pypy"',
  'safety',
  # Semgrep crashing on Github Actions PyPy. (As of 2022-02-13.)
  'semgrep; implementation_name != "pypy"',
]
management = [
  'bump2version',
  'invoke',
  'tomli',
  'tomli-w',
  'twine',
]
test = [
  # Coverage 6.1 series breaks how we handle .gitignore files.
  'coverage[toml] >= 6.2',
  'hypothesis',
  'pytest',
]

[installation]

[optional-installation]
