name: fresheners
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
jobs:
  freshen:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: emcd/python-lockup/.github/actions/python-venv@master
      - name: Install Asdf and Pythons
        uses: asdf-vm/actions/install@v1
      - name: Freshen Project
        run: pipenv run invoke freshen
      # TODO: PGP key setup for bot.
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        permissions:
          contents: write
          pull-requests: write
        with:
          title: '[GHA] Freshen Project'
          commit-message: '[GHA] Freshen Project'
          # TODO: Committer which matches PGP key.
          branch: gha-freshener
          delete-branch: true
          reviewers: emcd
