name: fresheners
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
jobs:
  freshen:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: emcd/python-lockup/.github/actions/python-venv@test-gha-no-toolcaches
        with:
          python-version: all
      - name: Load PGP Key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          git_commit_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: '${{ secrets.GHA_COMMIT_SIGNING_KEY }}'
#      - name: Install Asdf and Pythons
#        uses: asdf-vm/actions/install@v1
      - name: DEBUG
        run: |
          python --version
          echo $PATH
          which pipenv
      - name: Freshen Project
        run: pipenv run invoke freshen
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: '[GHA] Freshen Project'
          commit-message: '[GHA] Freshen Project'
          committer: 'Github Actions Robot <emcd@users.noreply.github.com>'
          branch: gha-freshener
          delete-branch: true
          reviewers: emcd
