name: fresheners
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
jobs:

  freshen-tool-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Freshen Git Modules
        run: /usr/bin/python3 develop.py freshen-git-modules
        shell: bash
      - name: Install Asdf with Plugins
        uses: emcd/python-devshim/.github/actions/asdf-vm@master
      - name: Freshen Python Versions
        run: |
          set -eu
          declare -a versions
          # TODO: Pull versions from stored array.
          for version in '3.7' '3.8' '3.9' '3.10' 'pypy3.7' 'pypy3.8' 'pypy3.9' 'pyston-2.3'; do
            versions+=("$(asdf latest python ${version})")
          done
          sed --in-place --regexp-extended "s/^python.*\$/python ${versions[*]}/" .tool-versions
        shell: bash
      - name: Access Cache for Asdf Tool Versions
        uses: actions/cache@v3
        with:
          key: asdf-tool-versions--${{ hashFiles('.tool-versions') }}
          path: .tool-versions
          restore-keys: asdf-tool-versions

  install-pythons-with-packages-updates:
    runs-on: ubuntu-latest
    needs: freshen-tool-versions
    strategy:
      matrix:
        # TODO: Use 'fromJSON' to expand from stringified list.
        #   https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object
        python-version: ['3.7', '3.8', '3.9', '3.10', 'pypy3.7', 'pypy3.8', 'pypy3.9', 'pyston-2.3']
    steps:
      - name: Prepare Python Virtual Environment
        uses: emcd/python-devshim/.github/actions/python-venv@master
        with:
          python-version: '${{ matrix.python-version }}'
          use-versions-update: true
      - name: Freshen Git Modules
        run: /usr/bin/python3 develop.py freshen-git-modules
        shell: bash
      - name: Update Python Packages Fixtures
        run: /usr/bin/python3 develop.py freshen-python-packages
        shell: bash
      - name: Record Differences
        run: |
          set -eu
          git diff -- .local/configuration/pypackages.fixtures.toml >python-${{ matrix.python-version }}--pypackages.fixtures.toml.patch
        shell: bash
      - name: Store Differences
        uses: actions/upload-artifact@v3
        with:
          name: fresh-diffs--${{ github.run_id }}
          path: python-${{ matrix.python-version }}--pypackages.fixtures.toml.patch

  create-pull-request:
    runs-on: ubuntu-latest
    needs: install-pythons-with-packages-updates
    steps:
      - name: Prepare Python Virtual Environment
        uses: emcd/python-devshim/.github/actions/python-venv@master
      - name: Freshen Git Modules
        run: /usr/bin/python3 develop.py freshen-git-modules
        shell: bash
      - name: Freshen Git Hooks
        run: /usr/bin/python3 develop.py freshen-git-hooks
        shell: bash
      - name: Access Cache for Asdf Tool Versions
        uses: actions/cache@v3
        with:
          key: asdf-tool-versions
          path: .tool-versions
      - name: Restore Differences
        uses: actions/download-artifact@v3
        with:
          name: fresh-diffs--${{ github.run_id }}
          path: diffs
      - name: Apply Differences
        run: |
          set -eu
          ls -lR diffs
          for f in diffs/*.patch; do
            git apply --allow-empty $f
          done
        shell: bash
      - name: Load PGP Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          git_commit_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: '${{ secrets.GHA_COMMIT_SIGNING_KEY }}'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: '[GHA] Freshen Project'
          commit-message: '[GHA] Freshen Project'
          committer: 'Github Actions Robot <emcd@users.noreply.github.com>'
          branch: gha-freshener
          delete-branch: true
          reviewers: emcd
