name: fresheners
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
jobs:
  freshen:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: emcd/python-devshim/.github/actions/python-venv@v1.0a202210200017
        with:
          python-version: all
      - name: Load PGP Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          git_commit_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: '${{ secrets.GHA_COMMIT_SIGNING_KEY }}'
      - name: Freshen Project
        run: python3 develop.py freshen
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: '[GHA] Freshen Project'
          commit-message: '[GHA] Freshen Project'
          committer: 'Github Actions Robot <emcd@users.noreply.github.com>'
          branch: gha-freshener
          delete-branch: true
          reviewers: emcd
