name: publisher
on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ['tester']
    branches: ['master']
    types: ['completed']
jobs:
  initialize:
    uses: ./.github/workflows/reusable--initializer.yaml
  publish:
    needs: initialize
    uses: emcd/python-devshim/.github/workflows/reusable--publisher.yaml@prerelease-1.0a20240303
    secrets:
      GHA_COMMIT_SIGNING_KEY: '${{ secrets.GHA_COMMIT_SIGNING_KEY }}'
