name: reusable--tests
on: ['workflow_call']
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.6.15'
          - '3.7.12'
          - '3.8.12'
          - '3.9.9'
          - '3.10.1'
          #- 'pyston-2.3.1'
          #- 'pypy3.7-7.3.7'
          #- 'pypy3.8-7.3.7'
    steps:
      - name: Prepare
        uses: emcd/python-lockup/.github/actions/python-venv@test-gha-no-toolcaches
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Test
        run: pipenv run invoke test
      - name: Preserve Coverage Results
        uses: actions/upload-artifact@v2
        with:
          name: coverage-results-${{ matrix.python-version }}
          path: caches/pytest/coverage.sqlite3.*
  # TODO: Add parallel job for test on 'TRACE_REFS' build of CPython.
