name: reusable--special-tester
on: ['workflow_call']
jobs:
  test-cpython-trace-refs:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: emcd/python-devshim/.github/actions/python-venv@stable
        with:
          python-version: '3.8'
          python-configure-flags: '--with-trace-refs'
      # Ensure that we can import the package successfully.
      # Cannot run test suite because of ABI incompatibility issues
      # with some dependencies.
      - name: Import Package
        run: |
          set -eu
          package_name="$(grep --extended-regexp '^name\s+=.*$' --max-count 1 pyproject.toml | sed --regexp-extended 's;name\s+=\s+;;' | tr --delete \')"
          python3 develop.py run "python -c 'import ${package_name}'"
        shell: bash
