name: tests
on:
  push:
    branches: ['master', 'release-*']
jobs:
  test:
    uses: emcd/python-lockup/.github/workflows/reusable--test.yaml@master
  report-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository Code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Procure Baseline Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Pipenv
        run: sudo pip3 install pipenv
      - name: Create Virtual Environment
        run: pipenv sync --dev
      - name: Restore Coverage Results
        uses: actions/download-artifact@v2
        with:
          path: caches/pytest
      - name: Relocate Coverage Results
        run: mv caches/pytest/coverage-results-*/coverage.sqlite3.* caches/pytest
      - name: Report Coverage
        run: pipenv run invoke report-coverage
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v2
        with:
          files: artifacts/coverage-pytest/coverage.xml
