name: tester
on:
  pull_request:
    branches: ['*']
  push:
    branches: ['master', 'release-*']
jobs:
  initialize:
    uses: ./.github/workflows/reusable--initializer.yaml
  test:
    needs: initialize
    strategy:
      matrix:
        python-version: ${{ fromJSON(needs.initialize.outputs.python-versions-json) }}
    uses: emcd/python-devshim/.github/workflows/reusable--tester.yaml@prerelease-1.0a20230114
    with:
      python-version: '${{ matrix.python-version }}'
  report:
    needs: test
    uses: emcd/python-devshim/.github/workflows/reusable--reporter.yaml@prerelease-1.0a20230114
    with:
      publish: "${{ 'master' == github.ref_name }}"
