# OBSOLETE. Serves as an anchor for tests status badge on older versions of the documentation.
#           Ran an actual test suite against the 'master' branch at one point.
name: tests
on:
  workflow_dispatch: {}
jobs:
  fabricate-truth:
    steps:
      - name: 'Not Volkswagen, Really...'
        run: true
