name: updater
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
jobs:
  initialize:
    uses: ./.github/workflows/reusable--initializer.yaml
  update:
    needs: initialize
    uses: emcd/python-devshim/.github/workflows/reusable--updater.yaml@prerelease-1.0a20240303
    secrets:
      GHA_COMMIT_SIGNING_KEY: '${{ secrets.GHA_COMMIT_SIGNING_KEY }}'
    with:
      python-versions-json: '${{ needs.initialize.outputs.python-versions-json }}'
      python-versions-words: '${{ needs.initialize.outputs.python-versions-words }}'
