name: upload-newest
on:
  workflow_run:
    workflows: ['tester']
    branches: ['master']
    types: ['completed']
jobs:
  upload-github-pages:
    runs-on: ubuntu-latest
    if: "${{ github.event.workflow_run.conclusion == 'success' }}"
    steps:
      - name: Prepare
        uses: emcd/python-devshim/.github/actions/python-venv@stable
      - name: Load PGP Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          git_commit_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: '${{ secrets.GHA_COMMIT_SIGNING_KEY }}'
      - name: Configure Git
        run: |
          git config user.name 'Github Actions Robot'
          git config user.email '${{ github.repository_owner }}@users.noreply.github.com'
      - name: Upload Github Pages
        run: /usr/bin/python3 develop.py upload-github-pages
        shell: bash
